title: Keeterial
description: Keeterial is a material-inspired Pages theme, built for Kee Projects and similar pages.
remote_theme: Kee7702/Keeterial
nav:
  test:
  - h: "https://nicknameopg.github.io/NicknameDev/assets/images/icon.png"
  - i: "https://nicknameopg.github.io/NicknameDev/assets/images/icon.png"
  - t: "image"
  test2:
  - h: "https://nicknameopg.github.io/NicknameDev/assets/images/icon.png"
  - i: "build"
  - t: "icon"
footer: Keeterial is a material-inspired Pages theme, built for Kee Projects and similar pages.
build_info: true
